# Generated by Django 4.1.3 on 2023-01-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('cni', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('carte_payement', models.CharField(max_length=16)),
                ('type_abonnement', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
