# Generated by Django 4.1.3 on 2023-01-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestmuseeapp', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_day',
            field=models.DateField(help_text='Date de fin de la Manifestation', verbose_name='Date de fin de la Manifestation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='static/img/manifestations'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_day',
            field=models.DateField(help_text='Date de début de la Manifestation', verbose_name='Date de début de la Manifestation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Nom de la Manifestation', max_length=100, verbose_name='Nom de la Manifestation'),
        ),
    ]
