# Generated by Django 4.1.3 on 2023-01-20 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestmuseeapp', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('date_deces', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField(max_length=200)),
                ('est_valable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestmuseeapp.personel')),
            ],
        ),
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_ouevre', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_assurence', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestmuseeapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('Conferencier', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('duree', models.IntegerField(help_text='Durée en minutes', verbose_name='Durée de la conférence')),
                ('image', models.ImageField(upload_to='static/img/conference')),
                ('notes', models.TextField(blank=True, null=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestmuseeapp.salle')),
            ],
        ),
    ]
