# Generated by Django 4.1.3 on 2023-01-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestmuseeapp', '0003_artist_personel_salle_schedule_oeuvre_conference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oeuvre',
            old_name='type_assurence',
            new_name='type_assurance',
        ),
        migrations.RenameField(
            model_name='oeuvre',
            old_name='type_ouevre',
            new_name='type_oeuvre',
        ),
        migrations.AddField(
            model_name='abonnee',
            name='type_abonne',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='image',
            field=models.ImageField(default=0, upload_to='static/img/oeuvres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salle',
            name='capacite',
            field=models.IntegerField(),
        ),
    ]
