# Generated by Django 4.1.3 on 2023-02-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestmuseeapp', '0004_rename_type_assurence_oeuvre_type_assurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('guidee', models.BooleanField(choices=[(True, 'Guidée'), (False, 'Non Guidée')])),
                ('nbr_pers', models.IntegerField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
            ],
        ),
    ]
